version: "3.7"

services:

  backend:
    build: ./backend
    environment:
      DB_USER:
      DB_PASSWORD:
      DB_NAME:
      DB_HOST:
    ports:
      - "8000:8000"
    volumes:
      - ./backend/setup.py:/code/setup.py
      - ./backend/alembic.ini:/code/alembic.ini
      - ./backend/readyupper:/code/readyupper

  database:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
