"""Add participation model

Revision ID: 599001156ed9
Revises: e85a3da692a0
Create Date: 2020-05-16 08:53:22.394905

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '599001156ed9'
down_revision = 'e85a3da692a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participation',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('calendar_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('entry_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('participant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'calendars', ['id'])
    op.create_unique_constraint(None, 'entries', ['id'])
    op.create_unique_constraint(None, 'participants', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='unique')
    op.drop_constraint(None, 'entries', type_='unique')
    op.drop_constraint(None, 'calendars', type_='unique')
    op.drop_table('participation')
    # ### end Alembic commands ###
