"""Add created field to calendar

Revision ID: 9a81bf13268d
Revises: e0a90296fcb2
Create Date: 2020-04-29 18:32:25.397446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a81bf13268d'
down_revision = 'e0a90296fcb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendars', 'created')
    # ### end Alembic commands ###
