"""Fix created timestamp defaults

Revision ID: d509bbfd00c5
Revises: 457ed8a8c62b
Create Date: 2020-05-03 09:59:37.264774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd509bbfd00c5'
down_revision = '457ed8a8c62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("calendars", "created", server_default=sa.func.now())
    op.alter_column("participants", "created", server_default=sa.func.now())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("calendars", "created", server_default="NOW()")
    op.alter_column("participants", "created", server_default="NOW()")
    # ### end Alembic commands ###
